#cp -rf .git ../ijkplayer-android_git_pp/
cp -rf bak.git .git
#cp -rf extra/soundtouch/.git/ ../ijkplayer-android_git_pp/extra/soundtouch/
cp -rf extra/soundtouch/bak.git extra/soundtouch/.git
cp -rf extra/libyuv/bak.git extra/libyuv/.git
#cp -rf extra/libyuv/.git/ ../ijkplayer-android_git_pp/extra/libyuv/
#cp -rf extra/ffmpeg/.git/ ../ijkplayer-android_git_pp/extra/ffmpeg/
cp -rf extra/ffmpeg/bak.git extra/ffmpeg/.git
#cp -rf ./ijkmedia/ijksoundtouch/.git ../ijkplayer-android_git_pp/ijkmedia/ijksoundtouch/
cp -rf ./ijkmedia/ijksoundtouch/bak.git ./ijkmedia/ijksoundtouch/.git
#cp -rf ./ijkmedia/ijkyuv/.git/ ../ijkplayer-android_git_pp/ijkmedia/ijkyuv/
cp -rf ./ijkmedia/ijkyuv/bak.git ./ijkmedia/ijkyuv/.git
#cp -rf ./android/contrib/ffmpeg-x86_64/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-x86_64/
cp -rf ./android/contrib/ffmpeg-x86_64/bak.git ./android/contrib/ffmpeg-x86_64/.git
#cp -rf ./android/contrib/ffmpeg-arm64/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-arm64/
cp -rf ./android/contrib/ffmpeg-arm64/bak.git ./android/contrib/ffmpeg-arm64/.git
#cp -rf ./android/contrib/ffmpeg-armv5/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-armv5/
cp -rf ./android/contrib/ffmpeg-armv5/bak.git ./android/contrib/ffmpeg-armv5/.git
#cp -rf ./android/contrib/ffmpeg-armv7a/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-armv7a/
cp -rf ./android/contrib/ffmpeg-armv7a/bak.git ./android/contrib/ffmpeg-armv7a/.git
cp -rf ./android/contrib/ffmpeg-x86/bak.git ./android/contrib/ffmpeg-x86/.git
