#cp -rf .git ../ijkplayer-android_git_pp/
cp -rf .git bak.git
#cp -rf extra/soundtouch/.git/ ../ijkplayer-android_git_pp/extra/soundtouch/
cp -rf extra/soundtouch/.git extra/soundtouch/bak.git
cp -rf extra/libyuv/.git extra/libyuv/bak.git
#cp -rf extra/libyuv/.git/ ../ijkplayer-android_git_pp/extra/libyuv/
#cp -rf extra/ffmpeg/.git/ ../ijkplayer-android_git_pp/extra/ffmpeg/
cp -rf extra/ffmpeg/.git extra/ffmpeg/bak.git
#cp -rf ./ijkmedia/ijksoundtouch/.git ../ijkplayer-android_git_pp/ijkmedia/ijksoundtouch/
cp -rf ./ijkmedia/ijksoundtouch/.git ./ijkmedia/ijksoundtouch/bak.git
#cp -rf ./ijkmedia/ijkyuv/.git/ ../ijkplayer-android_git_pp/ijkmedia/ijkyuv/
cp -rf ./ijkmedia/ijkyuv/.git ./ijkmedia/ijkyuv/bak.git
#cp -rf ./android/contrib/ffmpeg-x86_64/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-x86_64/
cp -rf ./android/contrib/ffmpeg-x86_64/.git ./android/contrib/ffmpeg-x86_64/bak.git
#cp -rf ./android/contrib/ffmpeg-arm64/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-arm64/
cp -rf ./android/contrib/ffmpeg-arm64/.git ./android/contrib/ffmpeg-arm64/bak.git
#cp -rf ./android/contrib/ffmpeg-armv5/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-armv5/
cp -rf ./android/contrib/ffmpeg-armv5/.git ./android/contrib/ffmpeg-armv5/bak.git
#cp -rf ./android/contrib/ffmpeg-armv7a/.git ../ijkplayer-android_git_pp/android/contrib/ffmpeg-armv7a/
cp -rf ./android/contrib/ffmpeg-armv7a/.git ./android/contrib/ffmpeg-armv7a/bak.git
cp -rf ./android/contrib/ffmpeg-x86/.git ./android/contrib/ffmpeg-x86/bak.git
